language: node_js
node_js:
  - "10"
cache: yarn
notifications:
  email: false

script:
  - yarn lint
  - yarn test
  - if [ $TRAVIS_BRANCH == "master" ]; then  yarn build && yarn test:stories --auto-accept-changes ; fi
  - if [ $TRAVIS_BRANCH != "master" ]; then  yarn build && yarn test:stories                       ; fi
