language: node_js
node_js:
  - "10"
cache: yarn
notifications:
  email: false

script:
  - yarn lint
  - yarn test
  - if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build && yarn test:stories-auto ; fi
  - if [ "$TRAVIS_BRANCH" != "master" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn build && yarn test:stories ; fi
