language: node_js
node_js:
  - "10"
cache: yarn
notifications:
  email: false
env:
  matrix:
    - CHROMATIC: "false"
      JEST_MAX_WORKERS: 4
    - CHROMATIC: "true"

script:
  - if [ "$CHROMATIC" == "false" ];                              then  yarn lint  && yarn test                               ; fi
  - if [ "$CHROMATIC" == "true"  && "$TRAVIS_BRANCH" == "next"]; then  yarn build && yarn test:stories --auto-accept-changes ; fi
  - if [ "$CHROMATIC" == "true"  && "$TRAVIS_BRANCH" != "next"]; then  yarn build && yarn test:stories                       ; fi
