name: Master Pipeline
on:
  push:
    branches:
      - master

jobs:
  build_test_and_deploy:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nuxt/actions-yarn@97f98f200b7fd42a001f88e7bdfc14d64d695ab2
      - run: yarn install
      - run: yarn test
      - run: yarn lint
      - uses: actions/npm@master
      - run: echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}' > .npmrc
      - run: yarn release-canary
